import { PlaceItem } from '../components/map/PlacePopup';

export const CURATED_PLACES_BY_CITY: Record<string, PlaceItem[]> = {
  'Đà Lạt': [
    {
      id: 'dl_1',
      name: 'Lẩu Gà Lá É Éo Lé (3/4)',
      category: 'dining',
      city: 'Đà Lạt',
      address: 'Đường 3 Tháng 4, Phường 3, Đà Lạt',
      lat: 11.9332,
      lng: 108.4410,
      price_level: 2,
      estimated_cost: 250000,
      opening_hours: '07:00 - 22:00',
      social_review_quote: 'Lẩu gà ngon béo ngậy giữa cái se lạnh Đà Lạt, nước lẩu đậm đà thơm mùi lá é!',
      social_review_url: 'https://www.tiktok.com/search?q=lau%20ga%20la%20e%20da%20lat',
      google_map_url: 'https://maps.google.com/?q=Lau+Ga+La+E+Tao+Ngoc+3/4+Da+Lat',
    },
    {
      id: 'dl_2',
      name: 'Bánh Mì Cối Xay Gió',
      category: 'dining',
      city: 'Đà Lạt',
      address: '19 Tăng Bạt Hổ, Phường 1, Đà Lạt',
      lat: 11.9421,
      lng: 108.4372,
      price_level: 1,
      estimated_cost: 35000,
      opening_hours: '06:00 - 22:00',
      social_review_quote: 'Bức tường vàng thần thánh check-in Đà Lạt và bánh mì pate siêu nhiều giòn rụm.',
      social_review_url: 'https://www.tiktok.com/search?q=coi%20xay%20gio%20da%20lat',
      google_map_url: 'https://maps.google.com/?q=Coi+Xay+Gio+Da+Lat',
    },
    {
      id: 'dl_3',
      name: 'Quán Cà Phê Túi Mơ To',
      category: 'cafe',
      city: 'Đà Lạt',
      address: 'Hẻm 31 Sào Nam, Phường 11, Đà Lạt',
      lat: 11.9485,
      lng: 108.4852,
      price_level: 2,
      estimated_cost: 65000,
      opening_hours: '07:00 - 21:30',
      social_review_quote: 'Vườn cúc họa mi trắng muốt view thung lũng lồng kính ngắm hoàng hôn đỉnh nhất Đà Lạt.',
      social_review_url: 'https://www.tiktok.com/search?q=tui%20mo%20to%20da%20lat',
      google_map_url: 'https://maps.google.com/?q=Tui+Mo+To+Coffee+Da+Lat',
    },
    {
      id: 'dl_4',
      name: 'Cheo Veo Cafe (Ngắm thung lũng)',
      category: 'cafe',
      city: 'Đà Lạt',
      address: '116 Hùng Vương, Hẻm Dã Chiến, Phường 11, Đà Lạt',
      lat: 11.9460,
      lng: 108.4720,
      price_level: 2,
      estimated_cost: 55000,
      opening_hours: '07:00 - 21:00',
      social_review_quote: 'Quán cà phê gỗ nhỏ ngắm rừng thông xanh mướt lung linh chiều hoàng hôn.',
      google_map_url: 'https://maps.google.com/?q=Cheo+Veo+Cafe+Da+Lat',
    },
    {
      id: 'dl_5',
      name: 'Ana Mandara Villas Dalat Resort & Spa',
      category: 'hotel',
      city: 'Đà Lạt',
      address: 'Đường Lê Lai, Phường 5, Đà Lạt',
      lat: 11.9455,
      lng: 108.4230,
      price_level: 4,
      estimated_cost: 2800000,
      opening_hours: '24/7',
      social_review_quote: 'Khu biệt thự Pháp cổ nằm ẩn mình giữa đồi thông thơ mộng.',
      google_map_url: 'https://maps.google.com/?q=Ana+Mandara+Villas+Dalat',
    },
    {
      id: 'dl_6',
      name: 'Chợ Đêm Đà Lạt & Quảng Trường Lâm Viên',
      category: 'attraction',
      city: 'Đà Lạt',
      address: 'Đường Nguyễn Thị Minh Khai, Phường 1, Đà Lạt',
      lat: 11.9395,
      lng: 108.4385,
      price_level: 1,
      estimated_cost: 100000,
      opening_hours: '17:00 - 23:30',
      social_review_quote: 'Thưởng thức bánh tráng nướng, nướng ngói và chụp ảnh Nụ Hoa Atiso khổng lồ.',
      google_map_url: 'https://maps.google.com/?q=Cho+Dem+Da+Lat',
    },
  ],
  'TP. Hồ Chí Minh': [
    {
      id: 'hcm_1',
      name: 'Nhà Thờ Đức Bà & Bưu Điện Trung Tâm',
      category: 'attraction',
      city: 'TP. Hồ Chí Minh',
      address: '01 Công xã Paris, Phường Bến Nghé, Quận 1, TP.HCM',
      lat: 10.7798,
      lng: 106.6990,
      price_level: 1,
      estimated_cost: 0,
      opening_hours: '07:30 - 17:00',
      social_review_quote: 'Biểu tượng kiến trúc Gothic độc đáo cổ kính bậc nhất Sài Thành.',
      google_map_url: 'https://maps.google.com/?q=Nha+Tho+Duc+Ba+Saigon',
    },
    {
      id: 'hcm_2',
      name: 'Phở Hòa Pasteur',
      category: 'dining',
      city: 'TP. Hồ Chí Minh',
      address: '260C Pasteur, Phường 8, Quận 3, TP.HCM',
      lat: 10.7876,
      lng: 106.6896,
      price_level: 2,
      estimated_cost: 95000,
      opening_hours: '06:00 - 22:30',
      social_review_quote: 'Tô phở bò truyền thống thơm lừng đậm đà lâu đời nhất Sài Gòn.',
      google_map_url: 'https://maps.google.com/?q=Pho+Hoa+Pasteur',
    },
    {
      id: 'hcm_3',
      name: 'Cà Phê Chung Cư 42 Nguyễn Huệ',
      category: 'cafe',
      city: 'TP. Hồ Chí Minh',
      address: '42 Nguyễn Huệ, Quận 1, TP.HCM',
      lat: 10.7745,
      lng: 106.7032,
      price_level: 2,
      estimated_cost: 60000,
      opening_hours: '08:00 - 22:30',
      social_review_quote: 'Chung cư nghệ thuật độc lạ tập hợp hàng chục quán cafe decor phong cách retro.',
      google_map_url: 'https://maps.google.com/?q=Chung+cu+42+Nguyen+Hue',
    },
    {
      id: 'hcm_4',
      name: 'Silverland Jolie Hotel & Spa',
      category: 'hotel',
      city: 'TP. Hồ Chí Minh',
      address: '4D Thi Sách, Bến Nghé, Quận 1, TP.HCM',
      lat: 10.7766,
      lng: 106.7058,
      price_level: 3,
      estimated_cost: 1500000,
      opening_hours: '24/7',
      social_review_quote: 'Khách sạn boutique phong cách cổ điển có hồ bơi ngắm sông Sài Gòn.',
      google_map_url: 'https://maps.google.com/?q=Silverland+Jolie+Hotel',
    },
  ],
  'Vũng Tàu': [
    {
      id: 'vt_1',
      name: 'Bánh Khọt Gốc Vú Sữa',
      category: 'dining',
      city: 'Vũng Tàu',
      address: '14 Nguyễn Trường Tộ, Phường 3, Vũng Tàu',
      lat: 10.3421,
      lng: 107.0765,
      price_level: 2,
      estimated_cost: 75000,
      opening_hours: '07:00 - 20:00',
      social_review_quote: 'Bánh khọt tôm tươi giòn rụm cuốn rau sống chấm nước mắm chua ngọt trứ danh Vũng Tàu.',
      google_map_url: 'https://maps.google.com/?q=Banh+Khot+Goc+Vu+Sua+Vung+Tau',
    },
    {
      id: 'vt_2',
      name: 'Tượng Chúa Kitô Vua (Núi Nhỏ)',
      category: 'attraction',
      city: 'Vũng Tàu',
      address: 'Thùy Vân, Phường 2, Vũng Tàu',
      lat: 10.3275,
      lng: 107.0848,
      price_level: 1,
      estimated_cost: 0,
      opening_hours: '07:00 - 17:00',
      social_review_quote: 'Leo 800 bậc thang lên vai Chúa ngắm trọn vẹn toàn cảnh biển Vũng Tàu bao la.',
      google_map_url: 'https://maps.google.com/?q=Tuong+Chua+Kito+Vung+Tau',
    },
    {
      id: 'vt_3',
      name: 'Soho Coffee Vũng Tàu (View biển)',
      category: 'cafe',
      city: 'Vũng Tàu',
      address: '66 Hạ Long, Phường 2, Vũng Tàu',
      lat: 10.3340,
      lng: 107.0720,
      price_level: 2,
      estimated_cost: 55000,
      opening_hours: '06:30 - 23:00',
      social_review_quote: 'Quán cafe tone trắng ngắm hoàng hôn ngắm biển đẹp ngất ngây.',
      google_map_url: 'https://maps.google.com/?q=Soho+Coffee+Vung+Tau',
    }
  ],
  'Hà Nội': [
    {
      id: 'hn_1',
      name: 'Phở Thìn Bờ Hồ',
      category: 'dining',
      city: 'Hà Nội',
      address: '61 Đinh Tiên Hoàng, Hoàn Kiếm, Hà Nội',
      lat: 21.0315,
      lng: 105.8523,
      price_level: 2,
      estimated_cost: 70000,
      opening_hours: '06:00 - 22:00',
      social_review_quote: 'Tô phở tái lăn thơm lừng vị gừng tỏi đặc trưng Hà Nội cổ.',
      google_map_url: 'https://maps.google.com/?q=Pho+Thin+Bo+Ho+Ha+Noi',
    },
    {
      id: 'hn_2',
      name: 'Cà Phê Giảng (Cà Phê Trứng)',
      category: 'cafe',
      city: 'Hà Nội',
      address: '39 Nguyễn Hữu Huân, Hoàn Kiếm, Hà Nội',
      lat: 21.0335,
      lng: 105.8540,
      price_level: 1,
      estimated_cost: 35000,
      opening_hours: '07:00 - 22:30',
      social_review_quote: 'Cà phê trứng béo ngậy trứ danh mảnh đất Hà Thành từ năm 1946.',
      google_map_url: 'https://maps.google.com/?q=Ca+Phe+Giang+Ha+Noi',
    },
    {
      id: 'hn_3',
      name: 'Hồ Hoàn Kiếm & Đền Ngọc Sơn',
      category: 'attraction',
      city: 'Hà Nội',
      address: 'Phố Đinh Tiên Hoàng, Hoàn Kiếm, Hà Nội',
      lat: 21.0285,
      lng: 105.8522,
      price_level: 1,
      estimated_cost: 30000,
      opening_hours: '07:00 - 18:00',
      social_review_quote: 'Trái tim của thủ đô với Cầu Thê Húc đỏ thắm và Tháp Rùa cổ kính.',
      google_map_url: 'https://maps.google.com/?q=Ho+Hoan+Kiem+Ha+Noi',
    },
    {
      id: 'hn_4',
      name: 'Bún Chả Hương Liên (Bún Chả Obama)',
      category: 'dining',
      city: 'Hà Nội',
      address: '24 Lê Văn Hưu, Hai Bà Trưng, Hà Nội',
      lat: 21.0185,
      lng: 105.8535,
      price_level: 2,
      estimated_cost: 65000,
      opening_hours: '08:00 - 20:30',
      social_review_quote: 'Suất bún chả kèm nem cua bể giòn tan nổi tiếng thế giới.',
      google_map_url: 'https://maps.google.com/?q=Bun+Cha+Huong+Lien+Ha+Noi',
    },
    {
      id: 'hn_5',
      name: 'Văn Miếu - Quốc Tử Giám',
      category: 'attraction',
      city: 'Hà Nội',
      address: '58 Quốc Tử Giám, Đống Đa, Hà Nội',
      lat: 21.0278,
      lng: 105.8355,
      price_level: 1,
      estimated_cost: 70000,
      opening_hours: '08:00 - 17:00',
      social_review_quote: 'Trường đại học đầu tiên của Việt Nam với kiến trúc cổ kính ngàn năm văn hiến.',
      google_map_url: 'https://maps.google.com/?q=Van+Mieu+Quoc+Tu+Giam+Ha+Noi',
    },
    {
      id: 'hn_6',
      name: 'Chùa Trấn Quốc & Hồ Tây',
      category: 'attraction',
      city: 'Hà Nội',
      address: 'Đường Thanh Niên, Tây Hồ, Hà Nội',
      lat: 21.0478,
      lng: 105.8368,
      price_level: 1,
      estimated_cost: 0,
      opening_hours: '07:30 - 17:00',
      social_review_quote: 'Ngôi chùa cổ nhất Thăng Long nằm trên bán đảo vàng giữa mặt Hồ Tây lộng gió.',
      google_map_url: 'https://maps.google.com/?q=Chua+Tran+Quoc+Ha+Noi',
    },
    {
      id: 'hn_7',
      name: 'Cà Phê Đinh (Ban công ngắm Hồ Gươm)',
      category: 'cafe',
      city: 'Hà Nội',
      address: 'Tầng 2, 13 Đinh Tiên Hoàng, Hoàn Kiếm, Hà Nội',
      lat: 21.0322,
      lng: 105.8520,
      price_level: 1,
      estimated_cost: 30000,
      opening_hours: '07:00 - 22:00',
      social_review_quote: 'Góc ban công nhỏ đậm chất Hà Nội xưa nhìn thẳng xuống mặt Hồ Gươm.',
      google_map_url: 'https://maps.google.com/?q=Ca+Phe+Dinh+Ha+Noi',
    },
    {
      id: 'hn_8',
      name: 'Phở Cuốn Hưng Bền (Ngũ Xã)',
      category: 'dining',
      city: 'Hà Nội',
      address: '118 Trấn Vũ, Ba Đình, Hà Nội',
      lat: 21.0445,
      lng: 105.8405,
      price_level: 2,
      estimated_cost: 80000,
      opening_hours: '09:00 - 22:00',
      social_review_quote: 'Phở cuốn thịt bò xào mềm ngọt và phở chiên phồng béo giòn đặc sản hồ Trúc Bạch.',
      google_map_url: 'https://maps.google.com/?q=Pho+Cuon+Hung+Ben+Ha+Noi',
    },
    {
      id: 'hn_9',
      name: 'Hoàng Thành Thăng Long',
      category: 'attraction',
      city: 'Hà Nội',
      address: '19C Hoàng Diệu, Ba Đình, Hà Nội',
      lat: 21.0352,
      lng: 105.8402,
      price_level: 1,
      estimated_cost: 70000,
      opening_hours: '08:00 - 17:00',
      social_review_quote: 'Di sản văn hóa thế giới lưu giữ dấu ấn lịch sử kinh thành ngàn năm.',
      google_map_url: 'https://maps.google.com/?q=Hoang+Thanh+Thang+Long+Ha+Noi',
    },
    {
      id: 'hn_10',
      name: 'La Siesta Classic Ma May Hotel',
      category: 'hotel',
      city: 'Hà Nội',
      address: '94 Mã Mây, Hàng Buồm, Hoàn Kiếm, Hà Nội',
      lat: 21.0355,
      lng: 105.8532,
      price_level: 3,
      estimated_cost: 1200000,
      opening_hours: '24/7',
      social_review_quote: 'Khách sạn boutique sang trọng ngay trung tâm Phố Cổ với rooftop bar tuyệt đẹp.',
      google_map_url: 'https://maps.google.com/?q=La+Siesta+Classic+Ma+May+Ha+Noi',
    }
  ]
};

export function getCuratedPlacesForCity(cityName: string): PlaceItem[] {
  const norm = (cityName || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd');
  
  if (norm.includes('da lat')) return CURATED_PLACES_BY_CITY['Đà Lạt'];
  if (norm.includes('ho chi minh') || norm.includes('sai gon') || norm.includes('hcm')) return CURATED_PLACES_BY_CITY['TP. Hồ Chí Minh'];
  if (norm.includes('vung tau')) return CURATED_PLACES_BY_CITY['Vũng Tàu'];
  if (norm.includes('ha noi')) return CURATED_PLACES_BY_CITY['Hà Nội'];
  
  // Default to Đà Lạt if city not explicitly listed
  return CURATED_PLACES_BY_CITY['Đà Lạt'];
}
