import { PlaceItem } from '../components/map/PlacePopup';

export const CURATED_PLACES_BY_CITY: Record<string, PlaceItem[]> = {
  'Đà Lạt': [
    {
      id: 'dl_1',
      name: 'Lẩu Gà Lá É Éo Lé (3/4)',
      category: 'dining',
      city: 'Đà Lạt',
      address: 'Đường 3 Tháng 4, Phường 3, Đà Lạt',
      lat: 11.9332,
      lng: 108.4410,
      price_level: 2,
      estimated_cost: 250000,
      opening_hours: '07:00 - 22:00',
      social_review_quote: 'Lẩu gà ngon béo ngậy giữa cái se lạnh Đà Lạt, nước lẩu đậm đà thơm mùi lá é!',
      social_review_url: 'https://www.tiktok.com/search?q=lau%20ga%20la%20e%20da%20lat',
      google_map_url: 'https://maps.google.com/?q=Lau+Ga+La+E+Tao+Ngoc+3/4+Da+Lat',
    },
    {
      id: 'dl_2',
      name: 'Bánh Mì Cối Xay Gió',
      category: 'dining',
      city: 'Đà Lạt',
      address: '19 Tăng Bạt Hổ, Phường 1, Đà Lạt',
      lat: 11.9421,
      lng: 108.4372,
      price_level: 1,
      estimated_cost: 35000,
      opening_hours: '06:00 - 22:00',
      social_review_quote: 'Bức tường vàng thần thánh check-in Đà Lạt và bánh mì pate siêu nhiều giòn rụm.',
      social_review_url: 'https://www.tiktok.com/search?q=coi%20xay%20gio%20da%20lat',
      google_map_url: 'https://maps.google.com/?q=Coi+Xay+Gio+Da+Lat',
    },
    {
      id: 'dl_3',
      name: 'Quán Cà Phê Túi Mơ To',
      category: 'cafe',
      city: 'Đà Lạt',
      address: 'Hẻm 31 Sào Nam, Phường 11, Đà Lạt',
      lat: 11.9485,
      lng: 108.4852,
      price_level: 2,
      estimated_cost: 65000,
      opening_hours: '07:00 - 21:30',
      social_review_quote: 'Vườn cúc họa mi trắng muốt view thung lũng lồng kính ngắm hoàng hôn đỉnh nhất Đà Lạt.',
      social_review_url: 'https://www.tiktok.com/search?q=tui%20mo%20to%20da%20lat',
      google_map_url: 'https://maps.google.com/?q=Tui+Mo+To+Coffee+Da+Lat',
    },
    {
      id: 'dl_4',
      name: 'Cheo Veo Cafe (Ngắm thung lũng)',
      category: 'cafe',
      city: 'Đà Lạt',
      address: '116 Hùng Vương, Hẻm Dã Chiến, Phường 11, Đà Lạt',
      lat: 11.9460,
      lng: 108.4720,
      price_level: 2,
      estimated_cost: 55000,
      opening_hours: '07:00 - 21:00',
      social_review_quote: 'Quán cà phê gỗ nhỏ ngắm rừng thông xanh mướt lung linh chiều hoàng hôn.',
      google_map_url: 'https://maps.google.com/?q=Cheo+Veo+Cafe+Da+Lat',
    },
    {
      id: 'dl_5',
      name: 'Ana Mandara Villas Dalat Resort & Spa',
      category: 'hotel',
      city: 'Đà Lạt',
      address: 'Đường Lê Lai, Phường 5, Đà Lạt',
      lat: 11.9455,
      lng: 108.4230,
      price_level: 4,
      estimated_cost: 2800000,
      opening_hours: '24/7',
      social_review_quote: 'Khu biệt thự Pháp cổ nằm ẩn mình giữa đồi thông thơ mộng.',
      google_map_url: 'https://maps.google.com/?q=Ana+Mandara+Villas+Dalat',
    },
    {
      id: 'dl_6',
      name: 'Chợ Đêm Đà Lạt & Quảng Trường Lâm Viên',
      category: 'attraction',
      city: 'Đà Lạt',
      address: 'Đường Nguyễn Thị Minh Khai, Phường 1, Đà Lạt',
      lat: 11.9395,
      lng: 108.4385,
      price_level: 1,
      estimated_cost: 100000,
      opening_hours: '17:00 - 23:30',
      social_review_quote: 'Thưởng thức bánh tráng nướng, nướng ngói và chụp ảnh Nụ Hoa Atiso khổng lồ.',
      google_map_url: 'https://maps.google.com/?q=Cho+Dem+Da+Lat',
    },
  ],
  'TP. Hồ Chí Minh': [
    {
      id: 'hcm_1',
      name: 'Nhà Thờ Đức Bà & Bưu Điện Trung Tâm',
      category: 'attraction',
      city: 'TP. Hồ Chí Minh',
      address: '01 Công xã Paris, Phường Bến Nghé, Quận 1, TP.HCM',
      lat: 10.7798,
      lng: 106.6990,
      price_level: 1,
      estimated_cost: 0,
      opening_hours: '07:30 - 17:00',
      social_review_quote: 'Biểu tượng kiến trúc Gothic độc đáo cổ kính bậc nhất Sài Thành.',
      google_map_url: 'https://maps.google.com/?q=Nha+Tho+Duc+Ba+Saigon',
    },
    {
      id: 'hcm_2',
      name: 'Phở Hòa Pasteur',
      category: 'dining',
      city: 'TP. Hồ Chí Minh',
      address: '260C Pasteur, Phường 8, Quận 3, TP.HCM',
      lat: 10.7876,
      lng: 106.6896,
      price_level: 2,
      estimated_cost: 95000,
      opening_hours: '06:00 - 22:30',
      social_review_quote: 'Tô phở bò truyền thống thơm lừng đậm đà lâu đời nhất Sài Gòn.',
      google_map_url: 'https://maps.google.com/?q=Pho+Hoa+Pasteur',
    },
    {
      id: 'hcm_3',
      name: 'Cà Phê Chung Cư 42 Nguyễn Huệ',
      category: 'cafe',
      city: 'TP. Hồ Chí Minh',
      address: '42 Nguyễn Huệ, Quận 1, TP.HCM',
      lat: 10.7745,
      lng: 106.7032,
      price_level: 2,
      estimated_cost: 60000,
      opening_hours: '08:00 - 22:30',
      social_review_quote: 'Chung cư nghệ thuật độc lạ tập hợp hàng chục quán cafe decor phong cách retro.',
      google_map_url: 'https://maps.google.com/?q=Chung+cu+42+Nguyen+Hue',
    },
    {
      id: 'hcm_4',
      name: 'Silverland Jolie Hotel & Spa',
      category: 'hotel',
      city: 'TP. Hồ Chí Minh',
      address: '4D Thi Sách, Bến Nghé, Quận 1, TP.HCM',
      lat: 10.7766,
      lng: 106.7058,
      price_level: 3,
      estimated_cost: 1500000,
      opening_hours: '24/7',
      social_review_quote: 'Khách sạn boutique phong cách cổ điển có hồ bơi ngắm sông Sài Gòn.',
      google_map_url: 'https://maps.google.com/?q=Silverland+Jolie+Hotel',
    },
  ],
  'Vũng Tàu': [
    {
      id: 'vt_1',
      name: 'Bánh Khọt Gốc Vú Sữa',
      category: 'dining',
      city: 'Vũng Tàu',
      address: '14 Nguyễn Trường Tộ, Phường 3, Vũng Tàu',
      lat: 10.3421,
      lng: 107.0765,
      price_level: 2,
      estimated_cost: 75000,
      opening_hours: '07:00 - 20:00',
      social_review_quote: 'Bánh khọt tôm tươi giòn rụm cuốn rau sống chấm nước mắm chua ngọt trứ danh Vũng Tàu.',
      google_map_url: 'https://maps.google.com/?q=Banh+Khot+Goc+Vu+Sua+Vung+Tau',
    },
    {
      id: 'vt_2',
      name: 'Tượng Chúa Kitô Vua (Núi Nhỏ)',
      category: 'attraction',
      city: 'Vũng Tàu',
      address: 'Thùy Vân, Phường 2, Vũng Tàu',
      lat: 10.3275,
      lng: 107.0848,
      price_level: 1,
      estimated_cost: 0,
      opening_hours: '07:00 - 17:00',
      social_review_quote: 'Leo 800 bậc thang lên vai Chúa ngắm trọn vẹn toàn cảnh biển Vũng Tàu bao la.',
      google_map_url: 'https://maps.google.com/?q=Tuong+Chua+Kito+Vung+Tau',
    },
    {
      id: 'vt_3',
      name: 'Soho Coffee Vũng Tàu (View biển)',
      category: 'cafe',
      city: 'Vũng Tàu',
      address: '66 Hạ Long, Phường 2, Vũng Tàu',
      lat: 10.3340,
      lng: 107.0720,
      price_level: 2,
      estimated_cost: 55000,
      opening_hours: '06:30 - 23:00',
      social_review_quote: 'Quán cafe tone trắng ngắm hoàng hôn ngắm biển đẹp ngất ngây.',
      google_map_url: 'https://maps.google.com/?q=Soho+Coffee+Vung+Tau',
    }
  ],
  'Hà Nội': [
    {
      id: 'hn_1',
      name: 'Phở Thìn Bờ Hồ',
      category: 'dining',
      city: 'Hà Nội',
      address: '61 Đinh Tiên Hoàng, Hoàn Kiếm, Hà Nội',
      lat: 21.0315,
      lng: 105.8523,
      price_level: 2,
      estimated_cost: 70000,
      opening_hours: '06:00 - 22:00',
      social_review_quote: 'Tô phở tái lăn thơm lừng vị gừng tỏi đặc trưng Hà Nội cổ.',
      google_map_url: 'https://maps.google.com/?q=Pho+Thin+Bo+Ho+Ha+Noi',
    },
    {
      id: 'hn_2',
      name: 'Cà Phê Giảng (Cà Phê Trứng)',
      category: 'cafe',
      city: 'Hà Nội',
      address: '39 Nguyễn Hữu Huân, Hoàn Kiếm, Hà Nội',
      lat: 21.0335,
      lng: 105.8540,
      price_level: 1,
      estimated_cost: 35000,
      opening_hours: '07:00 - 22:30',
      social_review_quote: 'Cà phê trứng béo ngậy trứ danh mảnh đất Hà Thành từ năm 1946.',
      google_map_url: 'https://maps.google.com/?q=Ca+Phe+Giang+Ha+Noi',
    },
    {
      id: 'hn_3',
      name: 'Hồ Hoàn Kiếm & Đền Ngọc Sơn',
      category: 'attraction',
      city: 'Hà Nội',
      address: 'Phố Đinh Tiên Hoàng, Hoàn Kiếm, Hà Nội',
      lat: 21.0285,
      lng: 105.8522,
      price_level: 1,
      estimated_cost: 30000,
      opening_hours: '07:00 - 18:00',
      social_review_quote: 'Trái tim của thủ đô với Cầu Thê Húc đỏ thắm và Tháp Rùa cổ kính.',
      google_map_url: 'https://maps.google.com/?q=Ho+Hoan+Kiem+Ha+Noi',
    },
    {
      id: 'hn_4',
      name: 'Bún Chả Hương Liên (Bún Chả Obama)',
      category: 'dining',
      city: 'Hà Nội',
      address: '24 Lê Văn Hưu, Hai Bà Trưng, Hà Nội',
      lat: 21.0185,
      lng: 105.8535,
      price_level: 2,
      estimated_cost: 65000,
      opening_hours: '08:00 - 20:30',
      social_review_quote: 'Suất bún chả kèm nem cua bể giòn tan nổi tiếng thế giới.',
      google_map_url: 'https://maps.google.com/?q=Bun+Cha+Huong+Lien+Ha+Noi',
    },
    {
      id: 'hn_5',
      name: 'Văn Miếu - Quốc Tử Giám',
      category: 'attraction',
      city: 'Hà Nội',
      address: '58 Quốc Tử Giám, Đống Đa, Hà Nội',
      lat: 21.0278,
      lng: 105.8355,
      price_level: 1,
      estimated_cost: 70000,
      opening_hours: '08:00 - 17:00',
      social_review_quote: 'Trường đại học đầu tiên của Việt Nam với kiến trúc cổ kính ngàn năm văn hiến.',
      google_map_url: 'https://maps.google.com/?q=Van+Mieu+Quoc+Tu+Giam+Ha+Noi',
    },
    {
      id: 'hn_6',
      name: 'Chùa Trấn Quốc & Hồ Tây',
      category: 'attraction',
      city: 'Hà Nội',
      address: 'Đường Thanh Niên, Tây Hồ, Hà Nội',
      lat: 21.0478,
      lng: 105.8368,
      price_level: 1,
      estimated_cost: 0,
      opening_hours: '07:30 - 17:00',
      social_review_quote: 'Ngôi chùa cổ nhất Thăng Long nằm trên bán đảo vàng giữa mặt Hồ Tây lộng gió.',
      google_map_url: 'https://maps.google.com/?q=Chua+Tran+Quoc+Ha+Noi',
    },
    {
      id: 'hn_7',
      name: 'Cà Phê Đinh (Ban công ngắm Hồ Gươm)',
      category: 'cafe',
      city: 'Hà Nội',
      address: 'Tầng 2, 13 Đinh Tiên Hoàng, Hoàn Kiếm, Hà Nội',
      lat: 21.0322,
      lng: 105.8520,
      price_level: 1,
      estimated_cost: 30000,
      opening_hours: '07:00 - 22:00',
      social_review_quote: 'Góc ban công nhỏ đậm chất Hà Nội xưa nhìn thẳng xuống mặt Hồ Gươm.',
      google_map_url: 'https://maps.google.com/?q=Ca+Phe+Dinh+Ha+Noi',
    },
    {
      id: 'hn_8',
      name: 'Phở Cuốn Hưng Bền (Ngũ Xã)',
      category: 'dining',
      city: 'Hà Nội',
      address: '118 Trấn Vũ, Ba Đình, Hà Nội',
      lat: 21.0445,
      lng: 105.8405,
      price_level: 2,
      estimated_cost: 80000,
      opening_hours: '09:00 - 22:00',
      social_review_quote: 'Phở cuốn thịt bò xào mềm ngọt và phở chiên phồng béo giòn đặc sản hồ Trúc Bạch.',
      google_map_url: 'https://maps.google.com/?q=Pho+Cuon+Hung+Ben+Ha+Noi',
    },
    {
      id: 'hn_9',
      name: 'Hoàng Thành Thăng Long',
      category: 'attraction',
      city: 'Hà Nội',
      address: '19C Hoàng Diệu, Ba Đình, Hà Nội',
      lat: 21.0352,
      lng: 105.8402,
      price_level: 1,
      estimated_cost: 70000,
      opening_hours: '08:00 - 17:00',
      social_review_quote: 'Di sản văn hóa thế giới lưu giữ dấu ấn lịch sử kinh thành ngàn năm.',
      google_map_url: 'https://maps.google.com/?q=Hoang+Thanh+Thang+Long+Ha+Noi',
    },
    {
      id: 'hn_10',
      name: 'La Siesta Classic Ma May Hotel',
      category: 'hotel',
      city: 'Hà Nội',
      address: '94 Mã Mây, Hàng Buồm, Hoàn Kiếm, Hà Nội',
      lat: 21.0355,
      lng: 105.8532,
      price_level: 3,
      estimated_cost: 1200000,
      opening_hours: '24/7',
      social_review_quote: 'Khách sạn boutique sang trọng ngay trung tâm Phố Cổ với rooftop bar tuyệt đẹp.',
      google_map_url: 'https://maps.google.com/?q=La+Siesta+Classic+Ma+May+Ha+Noi',
    },
    {
      id: 'hn_11',
      name: 'Chả Cá Lã Vọng',
      category: 'dining',
      city: 'Hà Nội',
      address: '14 Chả Cá, Hoàn Kiếm, Hà Nội',
      lat: 21.0368,
      lng: 105.8505,
      price_level: 3,
      estimated_cost: 180000,
      opening_hours: '11:00 - 21:00',
      social_review_quote: 'Đặc sản chả cá lăng nướng than hoa vàng rộm ăn kèm thì là hành hoa thơm nức.',
      google_map_url: 'https://maps.google.com/?q=Cha+Ca+La+Vong+Ha+Noi',
    },
    {
      id: 'hn_12',
      name: 'Phở Gia Truyền Bát Đàn',
      category: 'dining',
      city: 'Hà Nội',
      address: '49 Bát Đàn, Hoàn Kiếm, Hà Nội',
      lat: 21.0338,
      lng: 105.8479,
      price_level: 2,
      estimated_cost: 60000,
      opening_hours: '06:00 - 20:30',
      social_review_quote: 'Quán phở xếp hàng huyền thoại phố cổ với nước dùng trong veo ngọt thanh tự nhiên.',
      google_map_url: 'https://maps.google.com/?q=Pho+Bat+Dan+Ha+Noi',
    },
    {
      id: 'hn_13',
      name: 'Bánh Mì 25',
      category: 'dining',
      city: 'Hà Nội',
      address: '25 Hàng Cá, Hoàn Kiếm, Hà Nội',
      lat: 21.0371,
      lng: 105.8492,
      price_level: 1,
      estimated_cost: 35000,
      opening_hours: '07:00 - 21:00',
      social_review_quote: 'Bánh mì pate thập cẩm sốt đậm đà giòn rụm được du khách quốc tế mê mẩn.',
      google_map_url: 'https://maps.google.com/?q=Banh+Mi+25+Ha+Noi',
    },
    {
      id: 'hn_14',
      name: 'Bún Thang Bà Đức',
      category: 'dining',
      city: 'Hà Nội',
      address: '48 Cầu Gỗ, Hoàn Kiếm, Hà Nội',
      lat: 21.0318,
      lng: 105.8538,
      price_level: 2,
      estimated_cost: 55000,
      opening_hours: '07:00 - 22:00',
      social_review_quote: 'Bát bún thang cầu kỳ tinh tế đúng phong vị người Tràng An tao nhã.',
      google_map_url: 'https://maps.google.com/?q=Bun+Thang+Ba+Duc+Cau+Go+Ha+Noi',
    },
    {
      id: 'hn_15',
      name: 'Yên Cafe (Quán Thánh)',
      category: 'cafe',
      city: 'Hà Nội',
      address: '184 Quán Thánh, Ba Đình, Hà Nội',
      lat: 21.0425,
      lng: 105.8415,
      price_level: 2,
      estimated_cost: 40000,
      opening_hours: '07:30 - 18:00',
      social_review_quote: 'Món Sapa béo ngậy độc quyền kết hợp sữa tươi kem béo và cà phê thơm lừng.',
      google_map_url: 'https://maps.google.com/?q=Yen+Cafe+Quan+Thanh+Ha+Noi',
    },
    {
      id: 'hn_16',
      name: 'Loading T Cafe',
      category: 'cafe',
      city: 'Hà Nội',
      address: '8 Chân Cầm, Hàng Trống, Hoàn Kiếm, Hà Nội',
      lat: 21.0298,
      lng: 105.8493,
      price_level: 2,
      estimated_cost: 50000,
      opening_hours: '08:00 - 22:00',
      social_review_quote: 'Ngôi biệt thự Pháp cổ kính trăm năm rêu phong ngát hương cà phê quế hoa.',
      google_map_url: 'https://maps.google.com/?q=Loading+T+Cafe+Ha+Noi',
    },
    {
      id: 'hn_17',
      name: 'Serein Cafe & Lounge (View Cầu Long Biên)',
      category: 'cafe',
      city: 'Hà Nội',
      address: '16 Tập thể Ga Long Biên, Hoàn Kiếm, Hà Nội',
      lat: 21.0410,
      lng: 105.8499,
      price_level: 3,
      estimated_cost: 75000,
      opening_hours: '08:00 - 23:00',
      social_review_quote: 'Tầng thượng ngắm trọn vẹn đoàn tàu hỏa chạy qua cây cầu Long Biên lịch sử.',
      google_map_url: 'https://maps.google.com/?q=Serein+Cafe+Lounge+Ha+Noi',
    },
    {
      id: 'hn_18',
      name: 'Nhà Tù Hỏa Lò (Di Tích Lịch Sử)',
      category: 'attraction',
      city: 'Hà Nội',
      address: '1 Phố Hoả Lò, Trần Hưng Đạo, Hoàn Kiếm, Hà Nội',
      lat: 21.0252,
      lng: 105.8465,
      price_level: 1,
      estimated_cost: 50000,
      opening_hours: '08:00 - 17:00',
      social_review_quote: 'Điểm đến lịch sử xúc động nghẹn ngào với thuyết minh audio tour xuất sắc nhất thủ đô.',
      google_map_url: 'https://maps.google.com/?q=Nha+Tu+Hoa+Lo+Ha+Noi',
    },
    {
      id: 'hn_19',
      name: 'Nhà Hát Lớn Hà Nội',
      category: 'attraction',
      city: 'Hà Nội',
      address: '1 Tràng Tiền, Hoàn Kiếm, Hà Nội',
      lat: 21.0245,
      lng: 105.8578,
      price_level: 1,
      estimated_cost: 40000,
      opening_hours: '08:00 - 18:00',
      social_review_quote: 'Biểu tượng kiến trúc tân cổ điển Pháp tuyệt mỹ giữa lòng quảng trường Cách mạng.',
      google_map_url: 'https://maps.google.com/?q=Nha+Hat+Lon+Ha+Noi',
    },
    {
      id: 'hn_20',
      name: 'Cầu Long Biên (Chứng Nhân Lịch Sử)',
      category: 'attraction',
      city: 'Hà Nội',
      address: 'Cầu Long Biên, Hoàn Kiếm, Hà Nội',
      lat: 21.0435,
      lng: 105.8562,
      price_level: 1,
      estimated_cost: 0,
      opening_hours: '24/7',
      social_review_quote: 'Cây cầu thép vắt qua sông Hồng ngắm bình minh và hoàng hôn lãng mạn vô cùng.',
      google_map_url: 'https://maps.google.com/?q=Cau+Long+Bien+Ha+Noi',
    },
    {
      id: 'hn_21',
      name: 'Chợ Đêm Phố Cổ & Phố Đi Bộ',
      category: 'attraction',
      city: 'Hà Nội',
      address: 'Phố Hàng Đào - Hàng Ngang - Đồng Xuân, Hoàn Kiếm, Hà Nội',
      lat: 21.0345,
      lng: 105.8510,
      price_level: 1,
      estimated_cost: 0,
      opening_hours: '18:00 - 23:00 (T6, T7, CN)',
      social_review_quote: 'Thiên đường mua sắm quà lưu niệm, đồ thủ công và ăn vặt đường phố nhộn nhịp cuối tuần.',
      google_map_url: 'https://maps.google.com/?q=Cho+Dem+Pho+Co+Ha+Noi',
    },
    {
      id: 'hn_22',
      name: 'Bảo Tàng Mỹ Thuật Việt Nam',
      category: 'attraction',
      city: 'Hà Nội',
      address: '66 Nguyễn Thái Học, Ba Đình, Hà Nội',
      lat: 21.0305,
      lng: 105.8360,
      price_level: 1,
      estimated_cost: 40000,
      opening_hours: '08:30 - 17:00',
      social_review_quote: 'Kho tàng bảo vật quốc gia mỹ thuật hội họa và điêu khắc truyền thống Việt Nam.',
      google_map_url: 'https://maps.google.com/?q=Bao+Tang+My+Thuat+Viet+Nam+Ha+Noi',
    },
    {
      id: 'hn_23',
      name: 'Acoustic Hotel & Spa Phố Cổ',
      category: 'hotel',
      city: 'Hà Nội',
      address: '39 Thợ Nhuộm, Cửa Nam, Hoàn Kiếm, Hà Nội',
      lat: 21.0268,
      lng: 105.8475,
      price_level: 3,
      estimated_cost: 850000,
      opening_hours: '24/7',
      social_review_quote: 'Khách sạn phong cách boutique ấm cúng, phòng sạch đẹp tiện nghi cách Hồ Gươm 500m.',
      google_map_url: 'https://maps.google.com/?q=Acoustic+Hotel+Spa+Ha+Noi',
    },
    {
      id: 'hn_24',
      name: 'Hanoi Little Town Hotel',
      category: 'hotel',
      city: 'Hà Nội',
      address: '77 Bát Sứ, Hàng Bồ, Hoàn Kiếm, Hà Nội',
      lat: 21.0360,
      lng: 105.8490,
      price_level: 2,
      estimated_cost: 550000,
      opening_hours: '24/7',
      social_review_quote: 'Chỗ nghỉ giá cả hợp lý, nhân viên thân thiện nhiệt tình giữa lòng 36 phố phường.',
      google_map_url: 'https://maps.google.com/?q=Hanoi+Little+Town+Hotel',
    },
    {
      id: 'hn_25',
      name: 'The Chi Boutique Hotel Nhà Thờ',
      category: 'hotel',
      city: 'Hà Nội',
      address: '61 Nhà Chung, Hàng Trống, Hoàn Kiếm, Hà Nội',
      lat: 21.0280,
      lng: 105.8488,
      price_level: 3,
      estimated_cost: 1100000,
      opening_hours: '24/7',
      social_review_quote: 'Tọa độ lý tưởng đối diện Nhà Thờ Lớn, thiết kế hiện đại sang trọng.',
      google_map_url: 'https://maps.google.com/?q=The+Chi+Boutique+Hotel+Ha+Noi',
    },
    {
      id: 'hn_26',
      name: 'Chợ Đồng Xuân & Ngõ Đồng Xuân (Food Tour)',
      category: 'dining',
      city: 'Hà Nội',
      address: 'Ngõ Đồng Xuân, Hàng Xuân, Hoàn Kiếm, Hà Nội',
      lat: 21.0382,
      lng: 105.8495,
      price_level: 1,
      estimated_cost: 45000,
      opening_hours: '08:00 - 18:00',
      social_review_quote: 'Con ngõ ẩm thực trứ danh với bún ốc chuối đậu, bún chả que tre và bánh tôm giòn.',
      google_map_url: 'https://maps.google.com/?q=Ngo+Dong+Xuan+Ha+Noi',
    }
  ],
  'Hội An': [
    {
      id: 'ha_1',
      name: 'Bánh Mì Phượng',
      category: 'dining',
      city: 'Hội An',
      address: '2B Phan Châu Trinh, Cẩm Châu, Hội An',
      lat: 15.8778,
      lng: 108.3364,
      price_level: 1,
      estimated_cost: 35000,
      opening_hours: '06:30 - 21:30',
      social_review_quote: 'Bánh mì ngon nức tiếng với pate thơm béo, nước sốt thịt đậm đà trứ danh thế giới.',
      google_map_url: 'https://maps.google.com/?q=Banh+Mi+Phuong+Hoi+An',
    },
    {
      id: 'ha_2',
      name: 'Cơm Gà Bà Buội',
      category: 'dining',
      city: 'Hội An',
      address: '22 Phan Châu Trinh, Minh An, Hội An',
      lat: 15.8772,
      lng: 108.3315,
      price_level: 1,
      estimated_cost: 60000,
      opening_hours: '11:00 - 20:00',
      social_review_quote: 'Cơm gà vàng óng thơm lừng mỡ gà, thịt gà ta xé phay bóp gỏi hành tây chua ngọt đậm vị.',
      google_map_url: 'https://maps.google.com/?q=Com+Ga+Ba+Buoi+Hoi+An',
    },
    {
      id: 'ha_3',
      name: 'Cao Lầu Bá Lễ',
      category: 'dining',
      city: 'Hội An',
      address: '49/3 Trần Hưng Đạo, Sơn Phong, Hội An',
      lat: 15.8795,
      lng: 108.3325,
      price_level: 1,
      estimated_cost: 45000,
      opening_hours: '07:00 - 21:00',
      social_review_quote: 'Sợi mì cao lầu chuẩn giếng Bá Lễ dai giòn, thịt xíu mềm thơm đậm chất phố Hội.',
      google_map_url: 'https://maps.google.com/?q=Cao+Lau+Ba+Le+Hoi+An',
    },
    {
      id: 'ha_4',
      name: 'Bánh Đập Hến Xào Cẩm Nam',
      category: 'dining',
      city: 'Hội An',
      address: '679 Hai Bà Trưng, Cẩm Nam, Hội An',
      lat: 15.8752,
      lng: 108.3395,
      price_level: 1,
      estimated_cost: 50000,
      opening_hours: '08:00 - 20:00',
      social_review_quote: 'Hến xào xúc bánh tráng nướng giòn rụm chấm mắm nêm đậm đà bên bờ sông Hoài.',
      google_map_url: 'https://maps.google.com/?q=Hen+Xao+Cam+Nam+Hoi+An',
    },
    {
      id: 'ha_5',
      name: 'Faifo Coffee (Rooftop Phố Cổ)',
      category: 'cafe',
      city: 'Hội An',
      address: '130 Trần Phú, Minh An, Hội An',
      lat: 15.8775,
      lng: 108.3288,
      price_level: 2,
      estimated_cost: 65000,
      opening_hours: '07:00 - 21:30',
      social_review_quote: 'Tầng thượng ngắm trọn mái ngói âm dương rêu phong phố cổ Hội An siêu đẹp.',
      google_map_url: 'https://maps.google.com/?q=Faifo+Coffee+Hoi+An',
    },
    {
      id: 'ha_6',
      name: 'Hoi An Roastery (Châu Thượng Văn)',
      category: 'cafe',
      city: 'Hội An',
      address: '135 Trần Phú, Minh An, Hội An',
      lat: 15.8776,
      lng: 108.3292,
      price_level: 2,
      estimated_cost: 60000,
      opening_hours: '07:30 - 22:00',
      social_review_quote: 'Không gian nhà cổ gỗ mộc mạc thơm nức mùi cà phê rang xay nguyên chất.',
      google_map_url: 'https://maps.google.com/?q=Hoi+An+Roastery+Tran+Phu',
    },
    {
      id: 'ha_7',
      name: 'The Espresso Station',
      category: 'cafe',
      city: 'Hội An',
      address: '28/2 Trần Hưng Đạo, Minh An, Hội An',
      lat: 15.8802,
      lng: 108.3305,
      price_level: 2,
      estimated_cost: 55000,
      opening_hours: '07:30 - 17:30',
      social_review_quote: 'Quán cà phê ẩn mình trong con hẻm yên tĩnh với món cà phê than tre độc đáo.',
      google_map_url: 'https://maps.google.com/?q=The+Espresso+Station+Hoi+An',
    },
    {
      id: 'ha_8',
      name: 'Roving Chillhouse (Ngắm Lúa)',
      category: 'cafe',
      city: 'Hội An',
      address: 'Vòng xoay Cầu Đế Võng, Cẩm Châu, Hội An',
      lat: 15.8920,
      lng: 108.3520,
      price_level: 2,
      estimated_cost: 70000,
      opening_hours: '07:30 - 20:00',
      social_review_quote: 'Quán cà phê giữa cánh đồng lúa xanh mướt ngắm hoàng hôn cực chill và thư thái.',
      google_map_url: 'https://maps.google.com/?q=Roving+Chillhouse+Hoi+An',
    },
    {
      id: 'ha_9',
      name: 'Chùa Cầu & Phố Cổ Hội An',
      category: 'attraction',
      city: 'Hội An',
      address: 'Nguyễn Thị Minh Khai, Minh An, Hội An',
      lat: 15.8771,
      lng: 108.3259,
      price_level: 1,
      estimated_cost: 80000,
      opening_hours: '24/7',
      social_review_quote: 'Biểu tượng lịch sử văn hóa ngàn năm của đô thị cổ Hội An lung linh đèn lồng về đêm.',
      google_map_url: 'https://maps.google.com/?q=Chua+Cau+Hoi+An',
    },
    {
      id: 'ha_10',
      name: 'Hội Quán Phúc Kiến',
      category: 'attraction',
      city: 'Hội An',
      address: '46 Trần Phú, Cẩm Châu, Hội An',
      lat: 15.8778,
      lng: 108.3320,
      price_level: 1,
      estimated_cost: 40000,
      opening_hours: '07:00 - 17:30',
      social_review_quote: 'Công trình kiến trúc Trung Hoa lộng lẫy và thiêng liêng nhất phố cổ.',
      google_map_url: 'https://maps.google.com/?q=Hoi+Quan+Phuc+Kien+Hoi+An',
    },
    {
      id: 'ha_11',
      name: 'Rừng Dừa Bảy Mẫu Cẩm Thanh',
      category: 'attraction',
      city: 'Hội An',
      address: 'Võng Nhi, Cẩm Thanh, Hội An',
      lat: 15.8720,
      lng: 108.3650,
      price_level: 2,
      estimated_cost: 150000,
      opening_hours: '07:00 - 18:00',
      social_review_quote: 'Trải nghiệm đi thuyền thúng múa thúng giật gân vui nhộn giữa rừng dừa nước bạt ngàn.',
      google_map_url: 'https://maps.google.com/?q=Rung+Dua+Bay+Mau+Cam+Thanh',
    },
    {
      id: 'ha_12',
      name: 'Chợ Đêm Hội An & Thả Hoa Đăng Sông Hoài',
      category: 'attraction',
      city: 'Hội An',
      address: 'Nguyễn Hoàng, An Hội, Hội An',
      lat: 15.8760,
      lng: 108.3265,
      price_level: 1,
      estimated_cost: 50000,
      opening_hours: '17:00 - 23:00',
      social_review_quote: 'Dạo bước chợ đêm rực rỡ sắc màu đèn lồng và chèo thuyền thả đèn hoa đăng cầu an.',
      google_map_url: 'https://maps.google.com/?q=Cho+Dem+Hoi+An+Nguyen+Hoang',
    },
    {
      id: 'ha_13',
      name: 'Anantara Hoi An Resort',
      category: 'accommodation',
      city: 'Hội An',
      address: '1 Phạm Hồng Thái, Cẩm Châu, Hội An',
      lat: 15.8785,
      lng: 108.3382,
      price_level: 4,
      estimated_cost: 3200000,
      opening_hours: '24/7',
      social_review_quote: 'Khu nghỉ dưỡng 5 sao ven sông Thu Bồn sang trọng, không gian sân vườn Pháp cổ.',
      google_map_url: 'https://maps.google.com/?q=Anantara+Hoi+An+Resort',
    },
    {
      id: 'ha_14',
      name: 'Little Riverside Hoi An Luxury Hotel & Spa',
      category: 'accommodation',
      city: 'Hội An',
      address: '09 Phan Bội Châu, Cẩm Châu, Hội An',
      lat: 15.8788,
      lng: 108.3370,
      price_level: 3,
      estimated_cost: 1800000,
      opening_hours: '24/7',
      social_review_quote: 'Khách sạn boutique phong cách Đông Dương ven sông lãng mạn, hồ bơi vô cực ngắm hoàng hôn.',
      google_map_url: 'https://maps.google.com/?q=Little+Riverside+Hoi+An',
    },
    {
      id: 'ha_15',
      name: 'Vinh Hung Heritage Hotel Phố Cổ',
      category: 'accommodation',
      city: 'Hội An',
      address: '143 Trần Phú, Minh An, Hội An',
      lat: 15.8776,
      lng: 108.3298,
      price_level: 3,
      estimated_cost: 1200000,
      opening_hours: '24/7',
      social_review_quote: 'Khách sạn nhà cổ 200 năm tuổi ngay trung tâm phố cổ, trải nghiệm sống như quý tộc xưa.',
      google_map_url: 'https://maps.google.com/?q=Vinh+Hung+Heritage+Hotel+Hoi+An',
    }
  ]
};

export function getCuratedPlacesForCity(cityName: string): PlaceItem[] {
  const norm = (cityName || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd');
  
  if (norm.includes('da lat')) return CURATED_PLACES_BY_CITY['Đà Lạt'];
  if (norm.includes('ho chi minh') || norm.includes('sai gon') || norm.includes('hcm')) return CURATED_PLACES_BY_CITY['TP. Hồ Chí Minh'];
  if (norm.includes('hoi an')) return CURATED_PLACES_BY_CITY['Hội An'];
  if (norm.includes('vung tau')) return CURATED_PLACES_BY_CITY['Vũng Tàu'];
  if (norm.includes('ha noi')) return CURATED_PLACES_BY_CITY['Hà Nội'];
  
  return [];
}
